
development:
  adapter: mysql2
  host: localhost
  database: markcase_development
  username: root
  password: jay

production:
  adapter: mysql2
  host: localhost
  database: markcase_development
  username: root
  password: jay

test:
  adapter: mysql2
  host: localhost
  database: markcase_development
  username: root
  password: jay
