
development:
  adapter: mysql2
  port: 3306
  pool: 50
  host: localhost
  database: markcase_20150506
  username: markcase_dev
  password: "123456"

production:
  adapter: mysql2
  host: localhost
  database: markcase_development
  username: markcase_dev
  password: "123456"

test:
  adapter: mysql2
  host: localhost
  database: markcase_development
  username: markcase_dev
  password: "123456"
